name: Notification Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer le message
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "🚀 **Le site CryptoDigest est à jour !**\nLe code vient d’être modifié. Allez voir le résultat ici !"}' \
          "${{ secrets.DISCORD_WEBHOOK }}"