name: Notification Discord de déploiement

on:
  push:
    branches:
      - main  # Déclenche la notification à chaque push sur la branche main

jobs:
  discord-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Envoyer le message sur Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ https://discord.com/api/webhooks/1512845326933950464/D39zHwZB3IXB4wXwHeNL8CAHfskzEOZyIID8akGsOgWlUzcKaZCt06VHKZ0o4vLNpjsh }}
          nodetail: true
          title: "🚀 Le site CryptoDigest vient d'être mis à jour !"
          description: "De nouvelles informations sur la crypto sont en ligne. Allez jeter un œil ! \n\n🔗 [Cliquez ici pour voir le site](https://cryptodigest-ruby.vercel.app/)"
          color: 0x00ff00  # Couleur verte pour le message